// Generated by CoffeeScript 1.6.3
(function() {
  requirejs.config({
    "baseUrl": "scripts/lib",
    "paths": {
      "app": "../app",
      "jquery": "jquery",
      "masonry": "masonry",
      "imagesLoaded": "imagesloaded.pkgd.min"
    }
  });

  requirejs(["app/main"]);

}).call(this);
