// Generated by CoffeeScript 1.6.3
(function() {
  var Tile;

  Tile = (function() {
    function Tile() {}

    Tile.prototype.display = function() {
      return console.log("displaying tile");
    };

    return Tile;

  })();

}).call(this);
