// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery'], function($) {
    var Button;
    return Button = (function() {
      Button.prototype.parent = null;

      Button.prototype.callback = null;

      function Button(parent, callback) {
        this.parent = parent;
        this.callback = callback;
      }

      Button.prototype.display = function() {
        this.parent.append("<img id='leaftr-load-button' width='64' src='assets/img/loadButton.png'>");
        return $('#leaftr-load-button').click(this.callback());
      };

      Button.prototype.hide = function() {
        return $('#leaftr-load-button').remove();
      };

      return Button;

    })();
  });

}).call(this);
