// Generated by CoffeeScript 1.6.3
(function() {
  define(["jquery", 'app/Leaftr'], function($, Leaftr) {
    return $.fn.extend({
      leaftr: function(options) {
        var leaftr, plugin_div, settings;
        plugin_div = this;
        settings = {
          width: '100%',
          height: '100%',
          max_element: 10,
          related_width: '100px',
          img_width: '100px',
          max_title_length: 50,
          city_code: [],
          department_code: []
        };
        settings = $.extend(settings, options);
        return leaftr = new Leaftr(plugin_div, settings);
      }
    });
  });

}).call(this);
