// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseUrl: 'js/lib',
    paths: {
      jquery: 'jquery'
    }
  });

  require(['tile'], function(Tile) {
    return jquery.fn.extend({
      leaftr: function(options) {
        return Tile.display();
      }
    });
  });

}).call(this);
